const GET = 'NEGOTIATION/GET'
const GET_SUCCESS = 'NEGOTIATION/GET/SUCCESS'
const GET_ERROR = 'NEGOTIATION/GET/ERROR'

const GET_FIELDS = 'NEGOTIATION/GET_FIELDS'
const GET_FIELDS_SUCCESS = 'NEGOTIATION/GET_FIELDS/SUCCESS'
const GET_FIELDS_ERROR = 'NEGOTIATION/GET_FIELDS/ERROR'

const PUT_COUNTER = 'NEGOTIATION/PUT_COUNTER'
const PUT_COUNTER_SUCCESS = 'NEGOTIATION/PUT_COUNTER/SUCCESS'
const PUT_COUNTER_ERROR = 'NEGOTIATION/PUT_COUNTER/ERROR'

const ACCEPT = 'NEGOTIATION/ACCEPT'
const ACCEPT_SUCCESS = 'NEGOTIATION/ACCEPT/SUCCESS'
const ACCEPT_ERROR = 'NEGOTIATION/ACCEPT/ERROR'

const REJECT = 'NEGOTIATION/REJECT'
const REJECT_SUCCESS = 'NEGOTIATION/REJECT/SUCCESS'
const REJECT_ERROR = 'NEGOTIATION/REJECT/ERROR'

const GET_CUSTOM_FITOUT = 'NEGOTIATION/GET_CUSTOM_FITOUT'
const GET_CUSTOM_FITOUT_SUCCESS = 'NEGOTIATION/GET_CUSTOM_FITOUT/SUCCESS'
const GET_CUSTOM_FITOUT_ERROR = 'NEGOTIATION/GET_CUSTOM_FITOUT/ERROR'
const PUT_CUSTOM_FITOUT = 'NEGOTIATION/PUT_CUSTOM_FITOUT'
const PUT_CUSTOM_FITOUT_SUCCESS = 'NEGOTIATION/PUT_CUSTOM_FITOUT/SUCCESS'
const PUT_CUSTOM_FITOUT_ERROR = 'NEGOTIATION/PUT_CUSTOM_FITOUT/ERROR'

const SAVE_SPECIAL_PROVISIONS = 'NEGOTIATION/PROVISIONS/SAVE'
const SAVE_SPECIAL_PROVISIONS_SUCCESS = 'NEGOTIATION/PROVISIONS/SUCCESS'
const SAVE_SPECIAL_PROVISIONS_ERROR = 'NEGOTIATION/PROVISIONS/ERROR'
const ACCEPT_SPECIAL_PROVISIONS = 'NEGOTIATION/PROVISIONS/ACCEPT'
const REJECT_SPECIAL_PROVISIONS = 'NEGOTIATION/PROVISIONS/REJECT'

const SELECT_FITOUT = 'NEGOTIATION/SELECT_FITOUT'
const SELECT_FITOUT_SUCCESS = 'NEGOTIATION/SELECT_FITOUT/SUCCESS'
const SELECT_FITOUT_ERROR = 'NEGOTIATION/SELECT_FITOUT/ERROR'

const DELETE_FITOUT = 'NEGOTIATION/DELETE_FITOUT'
const DELETE_FITOUT_SUCCESS = 'NEGOTIATION/DELETE_FITOUT/SUCCESS'
const DELETE_FITOUT_ERROR = 'NEGOTIATION/DELETE_FITOUT/ERROR'

const PUT_SIGN_LEASE_STATUS = 'NEGOTIATION/PUT/SIGN_LEASE_STATUS'
const PUT_SIGN_LEASE_STATUS_SUCCESS =
  'NEGOTIATION/PUT/SIGN_LEASE_STATUS/SUCCESS'
const PUT_SIGN_LEASE_STATUS_ERROR = 'NEGOTIATION/PUT/SIGN_LEASE_STATUS/ERROR'

const POST_SIGNER_INFO = 'NEGOTIATION/SIGNER_INFO/POST'
const GET_SIGNER_INFO = 'NEGOTIATION/SIGNER_INFO/GET'
const PUT_SIGNER_INFO = 'NEGOTIATION/SIGNER_INFO/PUT'
const SIGNER_INFO_SUCCESS = 'NEGOTIATION/SIGNER_INFO/SUCCESS'
const SIGNER_INFO_ERROR = 'NEGOTIATION/SIGNER_INFO/ERROR'
const ACCEPT_LEASE = 'NEGOTIATION/SIGNING/ACCEPT'
const SIGNERS = 'NEGOTIATION/SIGNERS/GET'
const SIGNERS_SUCCESS = 'NEGOTIATION/SIGNERS/SUCCESS'
const SIGNERS_ERROR = 'NEGOTIATION/SIGNERS/ERROR'

const GET_PREVIEW_LEASE = 'NEGOTIATION/PREVIEW_LEASE'
const GET_PREVIEW_LEASE_SUCCESS = 'NEGOTIATION/PREVIEW_LEASE/SUCCESS'
const GET_PREVIEW_LEASE_ERROR = 'NEGOTIATION/PREVIEW_LEASE/ERROR'

const GET_LEASE_DOC = 'NEGOTIATION/LEASE_DOC'

export default {
  GET,
  GET_SUCCESS,
  GET_ERROR,
  GET_FIELDS,
  GET_FIELDS_SUCCESS,
  GET_FIELDS_ERROR,
  PUT_COUNTER,
  PUT_COUNTER_SUCCESS,
  PUT_COUNTER_ERROR,
  ACCEPT,
  ACCEPT_SUCCESS,
  ACCEPT_ERROR,
  REJECT,
  REJECT_SUCCESS,
  REJECT_ERROR,
  GET_CUSTOM_FITOUT,
  GET_CUSTOM_FITOUT_SUCCESS,
  GET_CUSTOM_FITOUT_ERROR,
  PUT_CUSTOM_FITOUT,
  PUT_CUSTOM_FITOUT_SUCCESS,
  PUT_CUSTOM_FITOUT_ERROR,
  SAVE_SPECIAL_PROVISIONS,
  SAVE_SPECIAL_PROVISIONS_SUCCESS,
  SAVE_SPECIAL_PROVISIONS_ERROR,
  ACCEPT_SPECIAL_PROVISIONS,
  REJECT_SPECIAL_PROVISIONS,
  SELECT_FITOUT,
  SELECT_FITOUT_SUCCESS,
  SELECT_FITOUT_ERROR,
  DELETE_FITOUT,
  DELETE_FITOUT_SUCCESS,
  DELETE_FITOUT_ERROR,
  PUT_SIGN_LEASE_STATUS,
  PUT_SIGN_LEASE_STATUS_SUCCESS,
  PUT_SIGN_LEASE_STATUS_ERROR,
  POST_SIGNER_INFO,
  GET_SIGNER_INFO,
  PUT_SIGNER_INFO,
  SIGNER_INFO_SUCCESS,
  SIGNER_INFO_ERROR,
  ACCEPT_LEASE,
  SIGNERS,
  SIGNERS_SUCCESS,
  SIGNERS_ERROR,
  GET_PREVIEW_LEASE,
  GET_PREVIEW_LEASE_SUCCESS,
  GET_PREVIEW_LEASE_ERROR,
  GET_LEASE_DOC,
}
