const INIT = 'ENQUIRY/INIT'
const INIT_SUCCESS = 'ENQUIRY/INIT/SUCCESS'
const INIT_ERROR = 'ENQUIRY/INIT/ERROR'

const GET = 'ENQUIRY/GET'
const GET_SUCCESS = 'ENQUIRY/GET/SUCCESS'
const GET_ERROR = 'ENQUIRY/GET/ERROR'

const GET_DOCS = 'ENQUIRY/GET_DOCS'
const GET_DOCS_SUCCESS = 'ENQUIRY/GET_DOCS/SUCCESS'
const GET_DOCS_ERROR = 'ENQUIRY/GET_DOCS/ERROR'
const UPDATE_DOCS = 'ENQUIRY/UPDATE_DOCS'

const GET_DOC = 'ENQUIRY/GET_DOC'
const GET_DOC_SUCCESS = 'ENQUIRY/GET_DOC/SUCCESS'
const GET_DOC_ERROR = 'ENQUIRY/GET_DOC/ERROR'
const PUT_DOC_TYPE = 'ENQUIRY/PUT_DOC_TYPE'
const PUT_DOC_TYPE_SUCCESS = 'ENQUIRY/PUT_DOC_TYPE/SUCCESS'
const PUT_DOC = 'ENQUIRY/PUT_DOC'
const PUT_DOC_SUCCESS = 'ENQUIRY/PUT_DOC/SUCCESS'
const PUT_DOC_ERROR = 'ENQUIRY/PUT_DOC/ERROR'
const DELETE_DOC = 'ENQUIRY/DELETE_DOC'
const DELETE_DOC_SUCCESS = 'ENQUIRY/DELETE_DOC/SUCCESS'
const DELETE_DOC_ERROR = 'ENQUIRY/DELETE_DOC/ERROR'
const GET_STD_TEMPLATE = 'ENQUIRY/GET_STD_TEMPLATE'

const RESET_NOTIFICATIONS = 'ENQUIRY/RESET_NOTIFICATIONS'

export default {
  INIT,
  INIT_SUCCESS,
  INIT_ERROR,
  GET,
  GET_SUCCESS,
  GET_ERROR,
  GET_DOCS,
  GET_DOCS_SUCCESS,
  GET_DOCS_ERROR,
  UPDATE_DOCS,
  GET_DOC,
  GET_DOC_SUCCESS,
  GET_DOC_ERROR,
  PUT_DOC_TYPE,
  PUT_DOC_TYPE_SUCCESS,
  PUT_DOC,
  PUT_DOC_SUCCESS,
  PUT_DOC_ERROR,
  DELETE_DOC,
  DELETE_DOC_SUCCESS,
  DELETE_DOC_ERROR,
  GET_STD_TEMPLATE,
  RESET_NOTIFICATIONS,
}
