const AUTH_INIT = 'USER_AUTH_INIT'
const SIGNUP = 'USER_SIGNUP'
const LOGIN_INIT = 'USER_LOGIN_INIT'
const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const LOGIN_ERROR = 'USER_LOGIN_ERROR'
const LOGIN_END = 'USER_LOGIN_END'
const LOGOUT = 'LOGOUT'
const SHOW_SESSION_POPUP = 'USER_SESSION_SHOW_POPUP'
const PING = 'USER_SESSION_PING'
const AVATAR_GET = 'USER_AVATAR_GET'
const AVATAR_GET_ERROR = 'USER_AVATAR_GET_ERROR'
const AVATAR_GET_SUCCESS = 'USER_AVATAR_GET_SUCCESS'
const AVATAR_POST = 'USER_AVATAR_POST'
const AVATAR_POST_SUCCESS = 'USER_AVATAR_POST_SUCCESS'
const AVATAR_POST_ERROR = 'USER_AVATAR_POST_ERROR'
const PROFILE_GET = 'USER_PROFILE_GET'
const PROFILE_GET_ERROR = 'USER_PROFILE_GET_ERROR'
const PROFILE_GET_SUCCESS = 'USER_PROFILE_GET_SUCCESS'
const PROFILE_PUT = 'USER_PROFILE_PUT'
const PROFILE_PUT_ERROR = 'USER_PROFILE_PUT_ERROR'
const PROFILE_PUT_SUCCESS = 'USER_PROFILE_PUT_SUCCESS'
const CHANGE_LOCALE = 'CHANGE_LOCALE'

export default {
  AUTH_INIT,
  LOGIN_INIT,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGIN_END,
  LOGOUT,
  SIGNUP,
  SHOW_SESSION_POPUP,
  PING,
  AVATAR_GET,
  AVATAR_GET_ERROR,
  AVATAR_GET_SUCCESS,
  AVATAR_POST,
  AVATAR_POST_ERROR,
  AVATAR_POST_SUCCESS,
  PROFILE_GET,
  PROFILE_GET_ERROR,
  PROFILE_GET_SUCCESS,
  PROFILE_PUT,
  PROFILE_PUT_ERROR,
  PROFILE_PUT_SUCCESS,
  CHANGE_LOCALE,
}
