const CHANGE_FILTER = 'SEARCH/CHANGE_FILTER'
const SEARCH_INIT = 'SEARCH/INIT'
const SEARCH_SUCCESS = 'SEARCH/SUCCESS'
const SEARCH_ERROR = 'SEARCH/ERROR'
const PUT_URL_PARAMS = 'SEARCH/PUT_URL_PARAMS'

export default {
  CHANGE_FILTER,
  SEARCH_INIT,
  SEARCH_SUCCESS,
  SEARCH_ERROR,
  PUT_URL_PARAMS,
}
