const DASHBOARD_INIT = 'DASHBOARD_INIT'
const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS'
const DASHBOARD_ERROR = 'DASHBOARD_ERROR'
const DASHBOARD_PENDING_SPACE_DELETE = 'DASHBOARD_PENDING_SPACE_DELETE'

export default {
  DASHBOARD_INIT,
  DASHBOARD_SUCCESS,
  DASHBOARD_ERROR,
  DASHBOARD_PENDING_SPACE_DELETE,
}
