const SEARCH_INIT = 'SPACE_SEARCH_INIT'
const SEARCH_SUCCESS = 'SPACE_SEARCH_SUCCESS'
const SEARCH_ERROR = 'SPACE_SEARCH_ERROR'
const GET_INIT = 'SPACE_GET_INIT'
const GET_SUCCESS = 'SPACE_GET_SUCCESS'
const GET_ERROR = 'SPACE_GET_ERROR'
const GET_SPACE = 'SPACE_GET_SPACE'
const GET_SPACE_SUCCESS = 'SPACE_GET_SPACE_SUCCESS'
const GET_SPACE_ERROR = 'SPACE_GET_SPACE_ERROR'
const GET_SELECTED_SPACE = 'SPACE_GET_SELECTED_SPACE'
const GET_SELECTED_SPACE_SUCCESS = 'SPACE_GET_SELECTED_SPACE_SUCCESS'
const GET_SELECTED_SPACE_ERROR = 'SPACE_GET_SELECTED_SPACE_ERROR'
const GET_PARENT_SPACE_SUCCESS = 'SPACE_GET_PARENT_SPACE_SUCCESS'
const GET_AMENITIES_SUCCESS = 'SPACE_GET_AMENITIES_SUCCESS'

export default {
  SEARCH_INIT,
  SEARCH_SUCCESS,
  SEARCH_ERROR,
  GET_INIT,
  GET_SUCCESS,
  GET_ERROR,
  GET_SPACE,
  GET_SPACE_SUCCESS,
  GET_SPACE_ERROR,
  GET_SELECTED_SPACE,
  GET_SELECTED_SPACE_SUCCESS,
  GET_SELECTED_SPACE_ERROR,
  GET_PARENT_SPACE_SUCCESS,
  GET_AMENITIES_SUCCESS,
}
