const GET = 'MYENQUIRIRES/GET'
const GET_SUCCESS = 'MYENQUIRIRES/GET/SUCCESS'
const GET_ERROR = 'MYENQUIRIRES/GET/ERROR'

const ACCEPT = 'MYENQUIRIRES/ACCEPT'
const ACCEPT_SUCCESS = 'MYENQUIRIRES/ACCEPT/SUCCESS'
const ACCEPT_ERROR = 'MYENQUIRIRES/ACCEPT/ERROR'

const REJECT = 'MYENQUIRIRES/REJECT'
const REJECT_SUCCESS = 'MYENQUIRIRES/REJECT/SUCCESS'
const REJECT_ERROR = 'MYENQUIRIRES/REJECT/ERROR'

const CANCEL = 'MYENQUIRIRES/CANCEL'
const CANCEL_SUCCESS = 'MYENQUIRIRES/CANCEL/SUCCESS'
const CANCEL_ERROR = 'MYENQUIRIRES/CANCEL/ERROR'

const SET_NOTIFICATIONS = 'NOTIFICATIONS/SET'
const GET_NOTIFICATIONS = 'NOTIFICATIONS/GET'

export default {
  GET,
  GET_SUCCESS,
  GET_ERROR,
  ACCEPT,
  ACCEPT_SUCCESS,
  ACCEPT_ERROR,
  REJECT,
  REJECT_SUCCESS,
  REJECT_ERROR,
  CANCEL,
  CANCEL_SUCCESS,
  CANCEL_ERROR,
  SET_NOTIFICATIONS,
  GET_NOTIFICATIONS,
}
