const GET = 'CHAT/GET'
const GET_SUCCESS = 'CHAT/GET/SUCCESS'
const GET_ERROR = 'CHAT/GET/ERROR'

const NEW_MESSAGE = 'CHAT/NEW_MESSAGE'
const NEW_MESSAGE_SUCCESS = 'CHAT/NEW_MESSAGE/SUCCESS'
const NEW_MESSAGE_ERROR = 'CHAT/NEW_MESSAGE/ERROR'

export default {
  GET,
  GET_SUCCESS,
  GET_ERROR,
  NEW_MESSAGE,
  NEW_MESSAGE_SUCCESS,
  NEW_MESSAGE_ERROR,
}
