const GET = 'APPOINTMENT/GET'
const GET_SUCCESS = 'APPOINTMENT/GET/SUCCESS'
const GET_ERROR = 'APPOINTMENT/GET/ERROR'
const UPDATE = 'APPOINTMENT/UPDATE'

const CREATE = 'APPOINTMENT/CREATE'
const CREATE_SUCCESS = 'APPOINTMENT/CREATE/SUCCESS'
const CREATE_ERROR = 'APPOINTMENT/CREATE/ERROR'

const ACCEPT = 'APPOINTMENT/ACCEPT'
const ACCEPT_SUCCESS = 'APPOINTMENT/ACCEPT/SUCCESS'
const ACCEPT_ERROR = 'APPOINTMENT/ACCEPT/ERROR'

const CANCEL = 'APPOINTMENT/CANCEL'
const CANCEL_SUCCESS = 'APPOINTMENT/CANCEL/SUCCESS'
const CANCEL_ERROR = 'APPOINTMENT/CANCEL/ERROR'

const CHANGE = 'APPOINTMENT/CHANGE'
const CHANGE_SUCCESS = 'APPOINTMENT/CHANGE/SUCCESS'
const CHANGE_ERROR = 'APPOINTMENT/CHANGE/ERROR'

export default {
  GET,
  GET_SUCCESS,
  GET_ERROR,
  UPDATE,
  CREATE,
  CREATE_SUCCESS,
  CREATE_ERROR,
  ACCEPT,
  ACCEPT_SUCCESS,
  ACCEPT_ERROR,
  CANCEL,
  CANCEL_SUCCESS,
  CANCEL_ERROR,
  CHANGE,
  CHANGE_SUCCESS,
  CHANGE_ERROR,
}
